analysis_models: TFT
checkpoint_directory: res
export_path: /tmp
filename_model_gpu: metrics-model-gpu.csv
filename_model_inference: metrics-model-inference.csv
gpu_output_fields:
- gpu_uuid
- batch_size
- concurrency
- gpu_used_memory
- gpu_free_memory
- gpu_utilization
- gpu_power_usage
inference_output_fields:
- batch_size
- concurrency
- perf_throughput
- perf_latency
- perf_client_send_recv
- perf_client_response_wait
- perf_server_queue
- perf_server_compute_input
- perf_server_compute_infer
- perf_server_compute_output
summarize: false
